package com.journalistjunction.initDB;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.journalistjunction.model.Location;
import com.journalistjunction.repository.LocationRepository;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;

@Service
@AllArgsConstructor
public class InitDbLocations {

    private final LocationRepository locationRepository;
    private final RestTemplate restTemplate;
    private final ObjectMapper objectMapper;

    public void seedDBLocations() {
        List<Location> allCountries = List.of(
                Location.builder().country("Afghanistan").cca2("AF").build(),
                Location.builder().country("Albania").cca2("AL").build(),
                Location.builder().country("Algeria").cca2("DZ").build(),
                Location.builder().country("Andorra").cca2("AD").build(),
                Location.builder().country("Angola").cca2("AO").build(),
                Location.builder().country("Antigua and Barbuda").cca2("AG").build(),
                Location.builder().country("Argentina").cca2("AR").build(),
                Location.builder().country("Armenia").cca2("AM").build(),
                Location.builder().country("Australia").cca2("AU").build(),
                Location.builder().country("Austria").cca2("AT").build(),
                Location.builder().country("Azerbaijan").cca2("AZ").build(),
                Location.builder().country("Bahamas").cca2("BS").build(),
                Location.builder().country("Bahrain").cca2("BH").build(),
                Location.builder().country("Bangladesh").cca2("BD").build(),
                Location.builder().country("Barbados").cca2("BB").build(),
                Location.builder().country("Belarus").cca2("BY").build(),
                Location.builder().country("Belgium").cca2("BE").build(),
                Location.builder().country("Belize").cca2("BZ").build(),
                Location.builder().country("Benin").cca2("BJ").build(),
                Location.builder().country("Bhutan").cca2("BT").build(),
                Location.builder().country("Bolivia").cca2("BO").build(),
                Location.builder().country("Bosnia and Herzegovina").cca2("BA").build(),
                Location.builder().country("Botswana").cca2("BW").build(),
                Location.builder().country("Brazil").cca2("BR").build(),
                Location.builder().country("Brunei").cca2("BN").build(),
                Location.builder().country("Bulgaria").cca2("BG").build(),
                Location.builder().country("Burkina Faso").cca2("BF").build(),
                Location.builder().country("Burundi").cca2("BI").build(),
                Location.builder().country("Cabo Verde").cca2("CV").build(),
                Location.builder().country("Cambodia").cca2("KH").build(),
                Location.builder().country("Cameroon").cca2("CM").build(),
                Location.builder().country("Canada").cca2("CA").build(),
                Location.builder().country("Central African Republic").cca2("CF").build(),
                Location.builder().country("Chad").cca2("TD").build(),
                Location.builder().country("Chile").cca2("CL").build(),
                Location.builder().country("China").cca2("CN").build(),
                Location.builder().country("Colombia").cca2("CO").build(),
                Location.builder().country("Comoros").cca2("KM").build(),
                Location.builder().country("Congo (Congo-Brazzaville)").cca2("CG").build(),
                Location.builder().country("Costa Rica").cca2("CR").build(),
                Location.builder().country("Croatia").cca2("HR").build(),
                Location.builder().country("Cuba").cca2("CU").build(),
                Location.builder().country("Cyprus").cca2("CY").build(),
                Location.builder().country("Czechia (Czech Republic)").cca2("CZ").build(),
                Location.builder().country("Democratic Republic of the Congo").cca2("CD").build(),
                Location.builder().country("Denmark").cca2("DK").build(),
                Location.builder().country("Djibouti").cca2("DJ").build(),
                Location.builder().country("Dominica").cca2("DM").build(),
                Location.builder().country("Dominican Republic").cca2("DO").build(),
                Location.builder().country("Ecuador").cca2("EC").build(),
                Location.builder().country("Egypt").cca2("EG").build(),
                Location.builder().country("El Salvador").cca2("SV").build(),
                Location.builder().country("Equatorial Guinea").cca2("GQ").build(),
                Location.builder().country("Eritrea").cca2("ER").build(),
                Location.builder().country("Estonia").cca2("EE").build(),
                Location.builder().country("Eswatini").cca2("SZ").build(),
                Location.builder().country("Ethiopia").cca2("ET").build(),
                Location.builder().country("Fiji").cca2("FJ").build(),
                Location.builder().country("Finland").cca2("FI").build(),
                Location.builder().country("France").cca2("FR").build(),
                Location.builder().country("Gabon").cca2("GA").build(),
                Location.builder().country("Gambia").cca2("GM").build(),
                Location.builder().country("Georgia").cca2("GE").build(),
                Location.builder().country("Germany").cca2("DE").build(),
                Location.builder().country("Ghana").cca2("GH").build(),
                Location.builder().country("Greece").cca2("GR").build(),
                Location.builder().country("Grenada").cca2("GD").build(),
                Location.builder().country("Guatemala").cca2("GT").build(),
                Location.builder().country("Guinea").cca2("GN").build(),
                Location.builder().country("Guinea-Bissau").cca2("GW").build(),
                Location.builder().country("Guyana").cca2("GY").build(),
                Location.builder().country("Haiti").cca2("HT").build(),
                Location.builder().country("Holy See").cca2("VA").build(),
                Location.builder().country("Honduras").cca2("HN").build(),
                Location.builder().country("Hungary").cca2("HU").build(),
                Location.builder().country("Iceland").cca2("IS").build(),
                Location.builder().country("India").cca2("IN").build(),
                Location.builder().country("Indonesia").cca2("ID").build(),
                Location.builder().country("Iran").cca2("IR").build(),
                Location.builder().country("Iraq").cca2("IQ").build(),
                Location.builder().country("Ireland").cca2("IE").build(),
                Location.builder().country("Israel").cca2("IL").build(),
                Location.builder().country("Italy").cca2("IT").build(),
                Location.builder().country("Jamaica").cca2("JM").build(),
                Location.builder().country("Japan").cca2("JP").build(),
                Location.builder().country("Jordan").cca2("JO").build(),
                Location.builder().country("Kazakhstan").cca2("KZ").build(),
                Location.builder().country("Kenya").cca2("KE").build(),
                Location.builder().country("Kiribati").cca2("KI").build(),
                Location.builder().country("Kuwait").cca2("KW").build(),
                Location.builder().country("Kyrgyzstan").cca2("KG").build(),
                Location.builder().country("Laos").cca2("LA").build(),
                Location.builder().country("Latvia").cca2("LV").build(),
                Location.builder().country("Lebanon").cca2("LB").build(),
                Location.builder().country("Lesotho").cca2("LS").build(),
                Location.builder().country("Liberia").cca2("LR").build(),
                Location.builder().country("Libya").cca2("LY").build(),
                Location.builder().country("Liechtenstein").cca2("LI").build(),
                Location.builder().country("Lithuania").cca2("LT").build(),
                Location.builder().country("Luxembourg").cca2("LU").build(),
                Location.builder().country("Madagascar").cca2("MG").build(),
                Location.builder().country("Malawi").cca2("MW").build(),
                Location.builder().country("Malaysia").cca2("MY").build(),
                Location.builder().country("Maldives").cca2("MV").build(),
                Location.builder().country("Mali").cca2("ML").build(),
                Location.builder().country("Malta").cca2("MT").build(),
                Location.builder().country("Marshall Islands").cca2("MH").build(),
                Location.builder().country("Mauritania").cca2("MR").build(),
                Location.builder().country("Mauritius").cca2("MU").build(),
                Location.builder().country("Mexico").cca2("MX").build(),
                Location.builder().country("Micronesia").cca2("FM").build(),
                Location.builder().country("Moldova").cca2("MD").build(),
                Location.builder().country("Monaco").cca2("MC").build(),
                Location.builder().country("Mongolia").cca2("MN").build(),
                Location.builder().country("Montenegro").cca2("ME").build(),
                Location.builder().country("Morocco").cca2("MA").build(),
                Location.builder().country("Mozambique").cca2("MZ").build(),
                Location.builder().country("Myanmar").cca2("MM").build(),
                Location.builder().country("Namibia").cca2("NA").build(),
                Location.builder().country("Nauru").cca2("NR").build(),
                Location.builder().country("Nepal").cca2("NP").build(),
                Location.builder().country("Netherlands").cca2("NL").build(),
                Location.builder().country("New Zealand").cca2("NZ").build(),
                Location.builder().country("Nicaragua").cca2("NI").build(),
                Location.builder().country("Niger").cca2("NE").build(),
                Location.builder().country("Nigeria").cca2("NG").build(),
                Location.builder().country("North Korea").cca2("KP").build(),
                Location.builder().country("North Macedonia").cca2("MK").build(),
                Location.builder().country("Norway").cca2("NO").build(),
                Location.builder().country("Oman").cca2("OM").build(),
                Location.builder().country("Pakistan").cca2("PK").build(),
                Location.builder().country("Palau").cca2("PW").build(),
                Location.builder().country("Palestine State").cca2("PS").build(),
                Location.builder().country("Panama").cca2("PA").build(),
                Location.builder().country("Papua New Guinea").cca2("PG").build(),
                Location.builder().country("Paraguay").cca2("PY").build(),
                Location.builder().country("Peru").cca2("PE").build(),
                Location.builder().country("Philippines").cca2("PH").build(),
                Location.builder().country("Poland").cca2("PL").build(),
                Location.builder().country("Portugal").cca2("PT").build(),
                Location.builder().country("Qatar").cca2("QA").build(),
                Location.builder().country("Romania").cca2("RO").build(),
                Location.builder().country("Russia").cca2("RU").build(),
                Location.builder().country("Rwanda").cca2("RW").build(),
                Location.builder().country("Saint Kitts and Nevis").cca2("KN").build(),
                Location.builder().country("Saint Lucia").cca2("LC").build(),
                Location.builder().country("Saint Vincent and the Grenadines").cca2("VC").build(),
                Location.builder().country("Samoa").cca2("WS").build(),
                Location.builder().country("San Marino").cca2("SM").build(),
                Location.builder().country("Sao Tome and Principe").cca2("ST").build(),
                Location.builder().country("Saudi Arabia").cca2("SA").build(),
                Location.builder().country("Senegal").cca2("SN").build(),
                Location.builder().country("Serbia").cca2("RS").build(),
                Location.builder().country("Seychelles").cca2("SC").build(),
                Location.builder().country("Sierra Leone").cca2("SL").build(),
                Location.builder().country("Singapore").cca2("SG").build(),
                Location.builder().country("Slovakia").cca2("SK").build(),
                Location.builder().country("Slovenia").cca2("SI").build(),
                Location.builder().country("Solomon Islands").cca2("SB").build(),
                Location.builder().country("Somalia").cca2("SO").build(),
                Location.builder().country("South Africa").cca2("ZA").build(),
                Location.builder().country("South Korea").cca2("KR").build(),
                Location.builder().country("South Sudan").cca2("SS").build(),
                Location.builder().country("Spain").cca2("ES").build(),
                Location.builder().country("Sri Lanka").cca2("LK").build(),
                Location.builder().country("Sudan").cca2("SD").build(),
                Location.builder().country("Suriname").cca2("SR").build(),
                Location.builder().country("Sweden").cca2("SE").build(),
                Location.builder().country("Switzerland").cca2("CH").build(),
                Location.builder().country("Syria").cca2("SY").build(),
                Location.builder().country("Tajikistan").cca2("TJ").build(),
                Location.builder().country("Tanzania").cca2("TZ").build(),
                Location.builder().country("Thailand").cca2("TH").build(),
                Location.builder().country("Timor-Leste").cca2("TL").build(),
                Location.builder().country("Togo").cca2("TG").build(),
                Location.builder().country("Tonga").cca2("TO").build(),
                Location.builder().country("Trinidad and Tobago").cca2("TT").build(),
                Location.builder().country("Tunisia").cca2("TN").build(),
                Location.builder().country("Turkey").cca2("TR").build(),
                Location.builder().country("Turkmenistan").cca2("TM").build(),
                Location.builder().country("Tuvalu").cca2("TV").build(),
                Location.builder().country("Uganda").cca2("UG").build(),
                Location.builder().country("Ukraine").cca2("UA").build(),
                Location.builder().country("United Arab Emirates").cca2("AE").build(),
                Location.builder().country("United Kingdom").cca2("GB").build(),
                Location.builder().country("United States of America").cca2("US").build(),
                Location.builder().country("Uruguay").cca2("UY").build(),
                Location.builder().country("Uzbekistan").cca2("UZ").build(),
                Location.builder().country("Vanuatu").cca2("VU").build(),
                Location.builder().country("Venezuela").cca2("VE").build(),
                Location.builder().country("Vietnam").cca2("VN").build(),
                Location.builder().country("Yemen").cca2("YE").build(),
                Location.builder().country("Zambia").cca2("ZM").build(),
                Location.builder().country("Zimbabwe").cca2("ZW").build()
        );

        locationRepository.saveAllAndFlush(allCountries);
    }
}
